stages:
  - build
  - test

# Debian 10 (Buster)
build:debian-buster:
  stage: build
  image: registry.pwmt.org/pwmt/gitlab-runner-images/debian:buster
  script:
    - mkdir -p build && cd build
    - meson ..
    - ninja
  artifacts:
    - build
  except:
    - tags

test:debian-buster:
  stage: test
  image: registry.pwmt.org/pwmt/gitlab-runner-images/debian:buster
  script:
    - cd build
    - ninja test
  dependencies:
    - build:debian-buster
  except:
    - tags
