Archlinux:
  image: pwmt-archlinux
  script:
    - make COLOR=0
    - make -C tests COLOR=0
    - make -C tests COLOR=0 run
  except:
    - tags

Debian 7:
  image: pwmt-debian-wheezy
  script:
    - make COLOR=0
    - make -C tests COLOR=0
    - make -C tests COLOR=0 run
  except:
    - tags

Debian 8:
  image: pwmt-debian-jessie
  script:
    - make COLOR=0
    - make -C tests COLOR=0
    - make -C tests COLOR=0 run
  except:
    - tags

Ubuntu 14.04:
  image: pwmt-ubuntu-trusty
  script:
    - make COLOR=0
    - make -C tests COLOR=0
    - make -C tests COLOR=0 run
  except:
    - tags

Ubuntu 15.04:
  image: pwmt-ubuntu-vivid
  script:
    - make COLOR=0
    - make -C tests COLOR=0
    - make -C tests COLOR=0 run
  except:
    - tags

Ubuntu 15.10:
  image: pwmt-ubuntu-wily
  script:
    - make COLOR=0
    - make -C tests COLOR=0
    - make -C tests COLOR=0 run
  except:
    - tags
